# This is a basic workflow to help you get started with Actions

name: My First Github Action

# Controls when the workflow will run
# Triggers the workflow on push request events 
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    #set matrix to ahdnle df=ifferent python version
    strategy:
      matrix:
        #this will run 2 jobs, one for each version
        python-version: [3.8,3.9]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{matrix.python-version}}
      - name: Install Dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        run: |
          cd scr
          python -m pytest addition.py
      
